### ISSUE TITLE
Add hardened materials

### ISSUE THREAD

**Issue by jaeschrich** [3Code5Me/deepcraft#1]
Add hardened stone, hardened dirt and hardened gravel.

**Comment by DJJBanx** [comment]
Hardened Stone - Blast Resist = 50.0f and Hardness = 10.0f and Tier = Iron
Hardened Dirt - Blast Resist = 30.0f and Hardness = 7.0f and Tier = Iron
Hardened Gravel - Blast Resist = 35.0f and Hardness = 5.0f and Tier = Iron

**Comment by jaeschrich** [comment]
What harvest levels should each block be at?
